# Generated by Django 4.1.4 on 2022-12-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
